# Generated by Django 5.1.1 on 2024-10-02 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MosqueAdmin',
            fields=[
                ('mosqueAdmin_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mosqueAdmin_username', models.CharField(max_length=50)),
                ('mosqueAdmin_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mosques',
            fields=[
                ('mosque_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mosque_name', models.CharField(max_length=100)),
                ('mosque_address', models.CharField(max_length=500)),
                ('mosque_google_map_url', models.URLField(max_length=500)),
                ('mosqueAdmin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigate.mosqueadmin')),
            ],
        ),
        migrations.CreateModel(
            name='Prayers',
            fields=[
                ('prayer_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('prayer_name', models.CharField(max_length=100)),
                ('prayer_rakat', models.IntegerField()),
                ('prayer_time', models.TimeField()),
                ('prayer_time_range', models.TimeField()),
                ('mosque_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigate.mosques')),
            ],
        ),
    ]
