# Generated by Django 5.1.1 on 2024-10-02 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prayers',
            old_name='prayer_time_range',
            new_name='prayer_valid_till',
        ),
    ]
