# Generated by Django 5.1.1 on 2024-10-02 06:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0002_rename_prayer_time_range_prayers_prayer_valid_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayers',
            name='azaan_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
