# Generated by Django 5.1.1 on 2024-10-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0004_alter_prayers_mosque_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayers',
            name='azaan_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='prayers',
            name='prayer_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='prayers',
            name='prayer_valid_till',
            field=models.TimeField(blank=True),
        ),
    ]
