# Generated by Django 5.1.1 on 2024-10-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0005_alter_prayers_azaan_time_alter_prayers_prayer_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayers',
            name='azaan_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prayers',
            name='prayer_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prayers',
            name='prayer_valid_till',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
