# Generated by Django 5.1.1 on 2024-10-05 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0008_prayers_mosqueadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prayers',
            old_name='mosque_id',
            new_name='mosque_name',
        ),
    ]
