# Generated by Django 5.1.1 on 2024-10-05 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0009_rename_mosque_id_prayers_mosque_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prayers',
            old_name='mosque_name',
            new_name='mosque_id',
        ),
    ]
