# Generated by Django 5.1.3 on 2024-11-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0013_remove_prayers_prayer_valid_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosques',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mosques',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
